service: rs-aws-backend-shop

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js

functions:
  hello:
    handler: "src/handler.hello"
    events:
      - http:
          path: hello
          method: any
